### ISSUE TITLE
Looking for additional inputs on module usage.

### ISSUE THREAD

**Issue by fslef** [Pwd9000-ML/terraform-azurerm-secure-backend#71]
Hello @Pwd9000-ML , 

Thank you for this great module.
I’ve read a lot of blog posts regarding how to provision a secure AzueRM backend, and your module is the most advanced one.

I’ve implemented the backend as explained in the documentation, including the migration of the backend state file, and everything is all right. Now I’m trying to understand how I should extend this to fit my needs.

Let’s consider the following structure

- A single tenant
  - 1 Management subscription
  - 1 DEV subscription
  - 1 Production subscription

In terms of deployment stages: I would like to keep these deployment steps independent:
-	1 global scope to deploy everything related to AAD
-	1 global scope to deploy everything related to cybersecurity settings
-	X deployment per ‘applications / infrastructure pattern’ (aka the landing zones)

For each deployment scope, I plan to use a dedicated SPN and a dedicated backend (Resource group, key vault, storage account).

My question is the following: How can I take advantage of using your module, to implement all the backends I need and how would you structure the code for it? This is the time when my skills are more limited and when I would need your advice

**Comment by Pwd9000-ML** [comment]
Hi @fslef 
This sounds to me like a really cool use-case you have. I am on holiday at the moment and will deff make contact with you when I am back to see hot to extend the module for this use case you mention.

Thanks,
Marcel.

**Comment by fslef** [comment]
Cool 😁

Enjoy your vacations and let's talk about it when you will be back.
(I would also be glad to contribute with my humble skills level)

Thank you,
François.

**Comment by Pwd9000-ML** [comment]
Hi @fslef, apologies for the delayed response, I will close this issue as you can have a look at this repo: https://github.com/Pwd9000-ML/Azure-Terraform-Deployments 
and blog post: https://dev.to/pwd9000/multi-environment-azure-deployments-with-terraform-and-github-2450 
I created, that explains how you can re-use modules in a multi environment deployment scenario which will fit your use case.
Thanks!
